INSERT INTO tags (taggroup_id, map, name) VALUES
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'zczcR\nccccR\ncccc=', 'Arelium'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'HHHH^\nH+H^^\nH|^^^', 'Dortlewall'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'y+cc.\nyyccy\nyyyyy', 'Newbie Village'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '.fyf.\nfffff\nyfff.', 'Mountaineer cottage'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '~~SSS\n~SSSc\n~Szcc', 'Laenor fort'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'sssss\nss?ss\nsssss', 'Woodhelven'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^^^hs\n^^?hh\n^wrrh', 'Revelstone'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'hhhhs\nhh?hs\nhhhhs', 'Seance''s platform'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 's^^^w\nss?hh\ns^^^^', 'Guards gap'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'rhhhh\nrr?hs\nhrrrs', 'Mithil'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'sssrs\nss?rr\nssrrs', 'Fouls creche'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fFFFF\nfF?Ff\nffFff', 'Elven village'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFFFF\nfF?ff\nfffff', 'Dunedains dark mansion'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fFFFF\nFf?ff\nffHfH', 'The Slopes of the Blackteeth Mountains'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFFFF\nFF?FF\nFFFFF', 'Elements'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^^^^^\n^^?H^\n^HH^H', 'Gauntlet event'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFFFF\nFF?FF\nFFFFF', 'Forest of Legolas'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFFFF\nFF?ff\nfffff', 'Abandoned Valley'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'yyyyy\nyf?,,\nyyyyy', 'Pluras castle'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '.####\nf#?##\n.#f#f', 'Shrine'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '.....\n..?..\n.....', 'White marble tower'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fffff\nff?ff\nfffff', 'Temple of Sarku'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '.....\n..!..\n.....', 'Monthy Python, Quest for the Holy Grail'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'HHH^^\nHH?^^\nH^^^^', 'Castle of Goddess'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^^^^^\n^^HHH\n^HH^H', 'Temple to the Winds'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'ff,ff\nff?ff\nfffff', 'Chateau de le Bigeaul'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fffff\nfFFFf\nFFFFf', 'Oakvale'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'ff,ff\n..?ff\n.....', 'Circus'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fffff\nll?f/\nfff+f', 'Hugoville and von Huber'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'ffff.\n.f?ff\n..fff', 'Orc scouts treehouse'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'f...h\n,,?hh\n..hhh', 'Drawbridge'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fFff.\nFF?ff\nFFFff', 'Newbie Forest'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'HH^^H\nHH?^^\n^HH^H', 'Raven, newbie mountain, trolls etc'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'H^^^^\nHH?^^\n^^^^^', 'Newbie Mountain'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fffyy\nyffyy\nyyyy/', 'Wibble'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fffyy\nyy?fy\nyyyyy', 'Petting Zoo'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'yfyyy\nyfyyy\nyfyyy', 'Arelium dungeons'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^^H^H\nH^H^H\nH^^HH', 'Newbie Mines'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'ryyy+\nyy?y.\nyyyy.', 'Newbie park'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^^HHH\n^^?HH\n^^HHH', 'Damned convent'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'yyyyy\nyy?yy\nyyffy', 'Bob and thelmas farm/grove'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'yyyyy\nyy?.y\nyy..y', 'Newbie playgrounds'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'yyFyy\n-----\nyyyyy', 'Nasu area'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'HHhhH\n^^?hh\n,,,,,', 'The Riddle of the Colours'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '.....\n..?..\n\\....', 'Newbie Playground'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fFFFF\n,,?FF\nfffFF', 'Peacock Farm'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFFFF\nFF?Ff\nFFFFf', 'Foxhunt'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '../..\n-+?FF\nFFFFF', 'Merchant subguild'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), ',^^^^\nH,?^^\nH,HHH', 'Therps castle'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'yyyyy\nyy?yy\nyy,yy', 'Farm'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FfffF\nFF?ff\nFFFff', 'Cathedral of Dr. Kilrathi'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFFFF\nFF?FF\nFFFFF', 'Alchemist Tower / Amazons'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFFFF\nfF?FF\nFFFFF', 'Alchemist Tower / Amazons, entrance 2'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'H^^^^\nHH?HH\nHHHHH', 'Darkcastle'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'hh#hh\nhh?##\nh###h', 'Chessboard'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFyyF\nFy?Ff\nFFFff', 'Gnomish flying machine'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '...ff\n..?Ff\nfFFff', 'Tower of the accursed'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '!^!^!\n!^?^!\n^^H^!', 'LAE-UNKNOWN '),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'hhfrh\nhh?rh\nfffrr', 'Zoy''s Inn'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '!!^^h\n!^?hh\n^hhhh', 'Nun Temple'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'f,FFF\nff?FF\nfffFF', 'Secladin'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '~SS~~\n~SbS~\n~SSS~', 'Faerie Island'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^^^^H\n^^fHh\nHhhHH', 'Faerie island'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^HHHH\n^^sHH\n^^^^^', 'Caverns of the Undying'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '.....\nff...\nfffff', 'Asylum'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'yyyyy\nyy...\nyy...', 'Enchanter (quest)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'ffff.\n.fff.\nffff.', 'Enchanter (corpse)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'HH^^^\nHHv^^\nHHHH^', 'Mountain Dwarves'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFFFF\nFFFFF\nFFFFF', 'Faerie Forest'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFFFF\nFFFFF\nFFFFF', 'Small Meadow'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'h##H^\n#HH#H\nH##hH', 'Ix''ixixiblat'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'hffff\nfffff\nfffff', 'Kender Mansion'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fffff\nfffff\nfffff', 'School of Lumine'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '.Ffff\nFFFff\nfFfff', 'Old Oak Forest'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'ff..f\nff.f.\nff...', 'Conifer Forest'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'hhhhh\n^^hhh\n^!^^^', 'Beastlands'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fff,f\nfffff\nfffff', 'Stouby'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fff|.\nffF|.\nfff+f', 'Wihne+ ss'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^H|HH\n^^cc^\n^cccc', 'Tyr Farwyn'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'Szzzz\nzz...\nz..,,', 'Landfall'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fffff\n.ffff\nfffff', 'Granny''s house'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFFFF\nFFFFF\nFFFFF', 'Wrebie forest'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'HHH^^\nH^H^^\n^H^^^', 'Bunny valley'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '....,\n...,.\n...,.', 'Lonely Inn'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'ffFff\nfffFf\n.ffFf', 'Butterfly farm'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fffff\nfffff\nfffff', 'Mesme'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fFFff\nfffff\nfffff', 'Forest of Moonrind'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'HH|HH\n^^?^^\n^^^^^', 'Iron mine'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^^^^^\n^^?^^\nHH|HH', 'Iron mine (south entrance)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '.##zz\n####z\n.,#zz', 'Sewers of Silverfang'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'SzSzz\nzzcc-\n..cc.', 'Vendace Shore'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'yyyyy\nyyyyy\nyyy+-', 'Fulgurite shop'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'H^^^^\nHH?^^\nHHHHH', 'Runemages guild northern entrance.'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^^^^H\n^^?^H\n^^HHH', 'Runemages guild, the eastern entrance.'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'H^^H^\n^^?HH\nH^^^H', 'Runemages guild, western entrance.'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'HHHHH\n^^?^^\n^^^^H', 'Tarmalen summer guild'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '....z\n..?..\n----+', 'Squire guild'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'zzSSS\n.z?SS\n./zzS', 'Shipyard'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^H^^^\nH^?^^\nH^H^^', 'Channelers'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '.+--=\n.|?.r\n.|..r', 'Knight guild'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^^^^H\n^^?H^\n^^^^^', 'Ranger guild'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'FFFFl\nFF?Fl\nFFFFl', 'Druids'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '^^hh#\nhh%##\nh^###', 'Mage magical'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'RcccR\nRcccR\nRcccR', 'Crimson'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), '..zzS\n...zS\n..zzS', 'Bruce''s shack'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'ycccy\nycccy\nycccy', 'Archer'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'fffff\n...ff\n...ff', 'Martial arts trainer (kobold)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'HH^^H\n^^HHH\n^HHHH', 'Barb (lae)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'sss..\nsssss\nsssss', 'Priest (lae)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'ffrrf\nffrrf\nffrff', 'River cavalier'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), 'zzf.|\n....|\n....+', 'Suicidal+ ss'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'cccc^\ncccc^\ncccc^', 'Shadowkeep'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '~~SSS\n~~?zz\n~f,zz', 'Shadowkeep annex'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'f^^!^\ny^h^^\ny^^h^', 'Tower of Horn-Durath'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 't^!^t\n^!?t^\nt^^^^', 'Frost giants'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^h^^\n^^?^^\n^^^^^', 'Lonely Mountain'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'ttttt\ntt?ht\nttttt', 'Dino''s taiga'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^^^^\nhh?^^\nhhhh^', 'Hells dojo'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^^^^\n^^?^^\n^^t^^', 'Frozen city of Rendburg'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'hhhht\nhh?hh\nhhhhh', 'Hill giants'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'ffffh\nff?Fh\nffFhF', 'Kalevala'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'fffff\nff?ff\nfffff', 'Abandoned study'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'fffff\nff?ff\nfffff', 'Cevi village'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'H####\nff?##\nff,ff', 'Barb guild event area'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'fffff\nff?ff\n-----', 'Campsite'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'h^^hh\nhh?hF\nFhhhF', 'Snowy peak'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'yyyyy\nyy?yy\nyyyyy', 'Knights & Dragons'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 's##s#\ns#?#f\ns#fff', 'Dark Forest'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'fffff\nff?ff\nfffff', 'Stonehenge'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '.fffF\n.,?FF\n,fFFF', 'Mirkhold'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^^^^\n^^?vv\n^^^^v', 'Caverns of Chaos'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'yy^^y\nff?ff\nfffff', 'Smurville'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'HHH^^\n^^fHr\n^^HHr', 'Nun guild mountain entrance'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^ff^\n^^?^^\n^^^^^', 'Kathvael forest'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^^^h\n^^^hh\n^^^hh', 'Mountains'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^^^^\n^^?^H\nHHHHH', 'Ackbar''s warrior shrine'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'ss,,,\nss?ss\nhhhhh', 'Paupers castle'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'FFFFF\nFF?FF\nFFFFF', 'Old forest'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'vvvvF\nvv?--\nvFFFv', 'Amberley mansion'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'fff~~\n--?S~\nfffff', 'Donaru'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'fffff\n-+?ff\nff\\ff', 'Inn of the Four Winds'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'ffff^\nff?ff\nfffff', 'Perilous forest'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '.....\n..?..\n....S', 'Doobies'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'Hz~~~\n,,?~~\n~HHH~', 'Lighthouse'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^^^v\n^^?fv\n^^^^f', 'Mountainpass+citadel'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'hh^^^\nHhf^^\nHHhh^', 'Inra'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'SffSS\nfh.fS\nh^hff', 'Dark church, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'hhhhf\nhhihh\nhhhhh', 'Harazam, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'fffff\nffyff\nffff,', 'Wormhole, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'rffvv\nrvffv\nrfffv', 'Creepy forest, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'sssss\nsssss\nsssss', 'Mushroom hill'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 't###h\n###hh\nh##hh', 'Ruins of untar trinit, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'hhhSS\nhhhSS\nhhffS', 'Norse village'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^^^f\n^^hff\n^^^^^', 'Stonetrolls'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'vvvvr\nvvvvr\nvvvvr', 'Spider cave, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'hhhhh\nhhhhh\nhhhhh', 'Old ladys shack, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'ff/^^\nf/v^^\n/^^^^', 'Swe+ ss'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'vvvvv\nvvvvv\nvvvvv', 'Hq1, warzone subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'vvvvv\nvvvvv\nvvvvv', 'Camp1, warzone subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'vvvvv\nvvvvv\nvvvvv', 'Warzone area'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'vvvvv\nvvvvv\nvvvvv', 'Camp2, warzone subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'vvvvv\nvvvvv\nvvvvv', 'Hq2, warzone subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'Fhrrr\nFFFrr\nFFFFr', 'Aldors village'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'hhh^^\nhhh^^\nhh^^h', 'Marble Shrine(?)'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'fffff\nfffff\nfffff', 'Attic'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'f###f\nf###f\nf###f', 'Ruins'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'h^^^^\nh^hh^\nhhh^^', 'Psi quest area'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'tHHHH\nHHttt\nHtttt', 'Trader''s House'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'fffff\nff.ff\nfffff', 'Moongate'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '~~~~~\n~~~~~\n~~~~~', 'ROTH-UNKNOWN '),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^^^h\nhhhhh\nhhhhh', 'Old Copper Mine'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'HHH^^\nHHH^^\nHHH^^', 'Hack'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'iiiii\niiiii\niiiii', 'Plateau of tsang'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'fffff\nfffff\nff|ff', 'Beaumont Hamel'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'HHhhh\nHhh^^\nhh^^h', 'Evil vale'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'rFFsF\nFFFFs\nFFFFF', 'Severus castle'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'HHHHH\nHHHvv\nHHvvh', 'Ranger (roth)'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'rrrrr\nsssss\nsssss', 'Priest (roth)'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '~~~~~\n~~h~~\n~~hhh', 'Skyrider cavalier'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'frrff\nfffff\nfffff', 'Martial arts trainer (gnoll)'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'h^^^h\n^^?hh\n^hhhh', 'Tarmalen winter guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^^^h\nhh?^^\nhhhhh', 'Beastmaster guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'HHHHh\nHH?hh\nH,hhh', 'Barb guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'v^^^^\nvv?^^\n^vv^^', 'Nun guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^^^!\n^^?!!\n^!!^^', 'Navigator guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '~~vvv\n~~?--\n~~vvv', 'Psionicist guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^ii^\n^t%^^\ntt^^^', 'Mage cold'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'Hhh^^\nhh%^^\nh^^^^', 'Mage asphyxiation'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'HHFFF\nHHFFF\nHHFFF', 'Tiger shrine (roth)'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'HHHhh\nvvvvv\nvvvvv', 'The Hall of One Thousand Voices'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'HHHHH\nHHHHH\nHsHHH', 'Riftwalker shaman cave'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'SShhS\nSh.hS\nShhSS', 'Crimson wyrm, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'ffhhf\nfhhhh\nhhhih', 'Green wyrm, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'fhffS\nffbSS\nfffSS', 'Blue wyrm, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^fff\n^^hff\n^^^ff', 'Goathead, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), 'ffffh\nffhff\nfffff', 'Redhawk, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), '^^vfr\n^^hfr\n^^ffr', 'Wyrms, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'Scccr\n~ccc-\n~c~Sr', 'Lorenchia'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '^^ddd\n^^d^d\n^^v^^', 'Valley of the Kings'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '~~~~~\n~y?yy\nyy|yy', 'Lucentium welcome center'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'ddddd\ndd?dd\nddddd', 'The Lost Pyramid'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'r=rr~\nr+?yy\n/fffy', 'Lands or lore'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '....d\n..?.d\nr....', 'Obelisk'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'fy/yy\ny/yyf\n/yyyy', 'Cornfield'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'ddd~~\n,,d~~\nddd~~', 'Lanzia'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'ddddd\n,,ddd\ndddd.', 'Colosseum'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'ffff,\nff,f,\nff,f,', 'Dahbec'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'yyffy\nfyyff\nyfyyy', 'Beanstalk'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '.ll.d\nlll.d\n.l..d', 'Oasis'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'yyy,f\nffyff\nyyyyy', 'Village of Shrea'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'ddddd\nddddd\nddddd', 'Nifties'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'f^^~~\n,,^f~\nfbbb~', 'Stagira'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'jFjFF\nFFjF.\n..,..', 'The Ruins of Astacia'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'rffff\nrffff\nrffff', 'Public Gardens'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'fhhhh\nffhhh\nfffyh', 'The Trilloch tower'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'fffff\nfffff\n....,', 'Anthill'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'ffffS\n--fSS\nfffff', 'Paladin Stronghold'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'FFFFF\nFFFFF\nFF+--', 'Tree village'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '~~SS~\n~SS~~\n~~~~S', 'Sunken ship'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'b..b~\nb..h~\nbhhh~', 'Giants/rechendak'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'bbbFF\nbbbFF\nFFFFF', 'Fraggle village'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '^^hhh\n^^h--\n^^hhh', 'Duzelton'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '~jrjy\njj~ry\njjjrj', 'Whirlpool'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'hh,yy\nhh,,y\nfhf,y', 'Land of the Overworld'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '..bSS\n..bbS\n...bS', 'Beach'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '.hhh^\nhhh^^\nhh^^^', 'Stifsim'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'SS~~S\nS~~~S\nS~~SS', 'Oystria'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '~~~~~\n~~c~~\n~~~~~', 'Silver lake'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '^^^^^\n~~^hh\n~~hhh', 'Karatur'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'sssss\nsssss\nsssss', 'Troglodytes'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'sssss\nsssss\nsssss', 'Steves hut, Troglodyte subarea'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '^^^^^\n^^^h^\n^^hhh', 'Mirror Mine'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'FFFFF\nFFvFF\nFFFFF', 'Earthquake event'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'FFFFF\nFFFFF\nFFFFF', 'Hailstorm event'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'FFFFF\nFFFFF\nFFFFF', 'Meteor shower event'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'FFFFF\nFFFFF\nFFFFF', 'Cyclone event tower'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'jjjjR\njjjjj\njjjjj', 'Pyran'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'h###j\n####j\nh###j', 'Adamantium chain'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'hhh^^\nhhd^^\nhh^^^', 'Templar shield quest cave'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'SSSSS\nbb~SS\nybbbS', 'Navigators of the sea'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'FFFF#\nFFFF#\nFFFFF', 'Old house'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'ddddd\nddddd\nddddd', 'Village of War'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'l.ddd\n...dd\nddddd', 'Village of Famine'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'ddddd\nddddd\nddddd', 'Village of Pestilence'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'ddddd\nddddd\nddddd', 'Village of Death'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'bbjbb\nSbbbS\nSSSSS', 'Clockwork observatory'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '.....\n..j..\n.....', 'Kirahvi+ ss'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'h^^^^\nhhh^^\nhhhh^', 'Underdark'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'SSSSS\nSSbbb\nSbfff', 'Satyr forest'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'fffff\nfffff\nffffH', 'A Tale of Two Towers'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'bbjjj\nSbbjj\nSSSSS', 'Catfolk shipyard'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'yyfff\nyyfff\nfyfff', 'Efiilas advance camp'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'fffff\nfffff\nfffff', 'Coffee forest'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'hhhhh\nh^hhh\n^^^^^', 'Draconian tower'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'hhh^^\nhhh^^\nhh^^^', 'Dwarf warehouse'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'ddddb\nddddb\nddddd', 'Gladiator training grounds'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'bjjbS\nbjjjb\nbbjjb', 'Ruins of Kofgaad'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'lfffl\nlffff\nlllfl', 'Monks'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'fffff\nfffff\nfffff', 'Alchemist guild'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'hhhdd\n^hhdd\n^dddd', 'Tarmalen autumn guild'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'jjjjj\njjjjj\njjjjj', 'Mage poison'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), '~j^^^\n~~^V^\n~jj^b', 'Mage guild, electricity'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'jjjjj\njjjjj\njssjj', 'Tiger shrine (luce)'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'jjjjj\nj^#^j\njjjj^', 'Temple of Tzarakk'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'srjjj\nsrjjj\n~~~~~', 'Martial arts trainer (catfolk)'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'bSSSS\n.bbSS\n....S', 'Ranger (luc)'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'hhhh^\n^^hhh\nrrrrh', 'Barb (luc)'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'sssss\nsssss\nsssss', 'Priest (luc)'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), 'FFFrR\njjjrR\njjjrR', 'Jungle cavalier'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'hhh^^\n^^h^^\n^^^^^', 'Aljerak temple'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^cccc\n=cccc\n^cccc', 'Rilynt''tar'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '~~SSF\n~~?SF\n~~|SF', 'Ril''ynttar harbour'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'FsFF~\nhh?F~\nsFss~', 'Elven Outpost'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '~~FFF\n~~?FF\n~~~FF', 'Manor'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'HHFFs\nFF?FF\nFFFsF', 'Samurai fort'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'ss~~~\nyy?S~\nyyyS~', 'Domgroth''s Mansion'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'sFFFF\nsF?FF\nFFFF/', 'Haunted Mansion'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'xxLL^\n^^?VL\n^^^L^', 'Volcano'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '@xxHH\n@^?HH\nV^^HH', 'Golem'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'FFFFF\nFF?FF\nFFFFF', 'Darkwood'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^^^^^\nH^?^^\nHHH\\-', 'Brantis'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '####x\n##?#x\nx#xxx', 'Perins'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'FFxxx\nxx?xx\nxxFFx', 'Mansion'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^^^^^\nhh?^^\n^hh^^', 'Tiamat'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'FxxFF\nFF?FF\nFFFFF', 'Temple of the Twisted Prophecies'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'hhhhh\nhh?,,\n^hhhh', 'Orthanc'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'hh^^^\n^h?^^\n^hh^^', 'Kutanakor, west entrance'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^^hh^\n^^?h^\n^^^h^', 'Kutanakor, east entrance'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^FFFF\nFF?FF\nFFFFh', 'Ikar'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^^^hh\n!^?hh\n^^hhL', 'Hell'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'sss^^\n~s?^^\n~~~~^', 'An old fort'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^^#^^\n^#?#^\n^hh^^', 'Tower of Corabandor'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'hVVVh\nVV?VV\nxxLLL', 'Fire giants'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'jjjjj\njj?jj\njjjjj', 'Ndoki'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'jjjjj\njj?jj\njjjjj', 'Cavemen'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '#h##b\n##?#b\n###bb', 'Atlantis'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'sFFFs\nFs?FF\nss,sF', 'Necromancer'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'FFFFF\nFs?FF\nFsFFF', 'Forest of the Moon'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'LLxxx\nLLxxx\nLLLxx', 'Castle Firefox'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'H^^^H\nx^L^H\n@@V^H', 'Citadel pit'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'hhhhh\n^^hhh\n^^^^h', 'Wanderer maze'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'sssss\nFFfss\nFsFFF', 'Abandoned house'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'SSjss\nrsjjj\nrsjjs', 'Trillazoo'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'sssss\nsssss\nsssss', 'Zonni swamps'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^^jjj\n^^jjj\n^^^jj', 'Savage jungle'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^^^^^\nHH?^^\nHHH^^', 'Cartwheel'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'FFFFF\n,,FFF\nFFFFF', 'Plakhstan'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), ',##ss\n,###s\n,##ss', 'Temple of Chaos'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '~~~ss\n~~sss\n~~~ss', 'Furnachia fort (west)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'ssSSS\nsssSS\nsssSS', 'Furnachia fort (east)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'jjj~~\n~~j~~\n~~~~~', 'Furnachia fort (south)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'ss+--\ns/FsF\n/sFFF', 'Abandoned village'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'hhh^^\nhhh^^\nh^^^^', 'Mountain peak'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'FFF#F\n#F#FF\nFFFFF', 'Abandoned, ruined temple'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'slH^H\nll#^^\nl^^^^', 'Drow tower'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^^#LV\n^^##L\n^#^##', 'Priest guild special place'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'sshs~\nhhhh~\nsh^h~', 'Infection'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'FFFFH\nFFFFF\nFFFFH', 'Monk (furn)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'HFFFF\nHHFFF\nH^HFF', 'Ranger (furn)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'HH^^H\nHHH^H\nHHH^H', 'Barb (furn)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^^^^^\n^^hhh\nhhhhh', 'Martial arts trainer (dwarf)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'HHHFF\nHH?FF\nHH^HF', 'Lords of chaos'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), '^^^^^\n^^?^^\nLL^^^', 'Wanderer''s guild'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'hhVLL\nLh%hL\nxxhLL', 'Mage fire'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), 'xxxxx\nxxxxx\nxxxxx', 'Badlands cavalier'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '^RcR^\nRcccR\n^RcR^', 'Calythien'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'HH~~~\n--?~~\nHHH~~', 'Windham'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'SSSSS\nSS?SS\nh,hhh', 'Seashore Tower'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'hFhhF\nFh?hh\n,,,,,', 'Dunamor'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'SSSSS\nhh?SS\n,,,hh', 'West wharf'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '~~~HH\n~~?HH\n~~v\\H', 'Sunderland'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'FHFHF\nFF?FF\nFFFFF', 'The Last Unicorn'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '..F.F\n.F?FF\n...F.', 'Teywaer Graveyard'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'h^^hh\n^^?Fh\n^FFFh', 'Teywaer Tunnel'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'FFFFF\nFF?FF\nFFFFF', 'Teywaer village'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '..F..\n.Ff..\n.FF.F', 'Teywaer well'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '^^^^^\n^^?^^\nvvv^^', 'Celestial Caverns'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'S...S\nSF..S\nh..SS', 'Goblin citadel'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'FFFFF\nFF?FF\nFFFFF', 'Well'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'rRvvv\nrR?vv\nrRrvv', 'Twisted tower'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'zh^^h\nh^?##\nzh##h', 'Cathedral'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '#####\n##?#l\n####l', 'Ruins of El Deagnoh'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '#^^^^\n#^?^^\n###^^', 'Halls of the Dead'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '^^^^v\n^^?vv\n^^vvv', 'Kobold mines'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'vvvvH\nvv?vv\nvvvvv', 'Tiburico'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'vvvvv\n^^?^^\n^^^^^', 'Castle of Toxic'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'h|h.S\nh+?.S\nhh\\.S', 'Seabird Inn'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '^^^HH\n^^?HH\n^^HHH', '51 daughters'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '^^^^^\nHH?^H\nsHHHH', 'The valley of silence'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'ff^^^\n--?^^\nHff^^', 'Tralpecktor'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'dddd^\ndd?dd\nddddd', 'The Ancient Temple of the Gods'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '~##..\n##?#h\n~##f.', 'Stone garden'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '^HHHH\n^^?HH\n^^^^^', 'The Warlock Conclave'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'ddddd\ndd?dd\nddddd', 'Tarackia'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'fffff\nff?fv\nff,ff', 'Brimshire'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'fffHv\nff?vv\nffvvv', 'Soy'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'fffff\nff?ff\nsffff', 'Hairikko Forest'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'vvvvv\nvv?vv\nvv|vv', 'The Temple of Pandion Knights'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'Hvvvv\nvv?vH\nvvvvH', 'Villager under attack'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'HH#HH\nH#?#H\nHH#HH', 'Ochimo'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'hhhhh\nsh?hS\nsh~SS', 'Red Tides'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'H^^^^\nHH?^^\nHH^^^', 'Caves of Orac'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'HH#H#\n##?#,\nv##HH', 'Ruins of a Temple of All Gods'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '####H\nH#?#H\nH####', 'DESO-UNKNOWN '),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'fsfss\nff?ss\nffHsf', 'Goblin Farm'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'fvHHH\nfv?Hf\nvvvHf', 'Mythical Valley'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'sssss\nsfsss\nffffs', 'Millie''s Nightmare'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'HyyFF\nHy?FF\nHH,Fl', 'Buckthorn Valley'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'fffff\nfffff\nfffff', 'The Lands of Apollo'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '^^^^~\n^^^^^\n^^svv', 'Magerathia'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'HH^^^\n...^^\n...^^', 'Tinmen Monastery'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'vvvvv\nvvvvv\nvvvvv', 'Abandoned barn'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '...ff\n.hhhf\nhhhhh', 'Snotling farm'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '^^^vv\n^^vvv\n^^vrr', 'Zorn'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'hhhhh\nhhhhh\nhhhhh', 'Feldspar conglomerate'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'vHHHH\nvvHHH\nvvvHH', 'Meadowshire'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '.....\n..,F.\nS,,.,', 'Broken Forest - Castle'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'S..,F\nSS,,.\n==,,,', 'Broken Forest - Barracks'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), ',.,.S\n,,,SS\nSSSSS', 'Broken Forest - Seacrest'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '...SS\nF.,SS\n.,.SS', 'Broken Forest - Prison'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'HHHHH\nHHHHH\nHHHHH', 'Ranger (deso)'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'HHH^^\n^^HH^\n^^^H^', 'Barb (deso)'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'sslls\nsssls\nsssss', 'Priest (deso)'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'HH#HH\nz###H\nHH#HH', 'Midnight cavalier'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'hssss\nhs%ss\nhssss', 'Mage acid'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'vv,^^\n^^?^^\n^^^^^', 'Templar guild'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'sssss\nss?sH\nsssss', 'Tarmalen spring guild'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '^^hhh\n^^?hh\n^^^hh', 'Conjurer guild'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '^dddH\ndd?#d\ndd##d', 'Reaver guild'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'HHH##\nHHH##\nHH###', 'Tiger shrine (deso)'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '^^^^d\nd^ddd\nddddd', 'Aelena temple'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), '/FFFF\nFFFFF\nFFFFF', 'Ghost liberator mansion'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'fffff\nfffff\nfffff', 'Animist guild'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), 'fffff\nfffff\nfffff', 'The Navigators of the Tree');
