INSERT INTO tags (taggroup_id, map, name) VALUES
  (1, E'zczcR\nccccR\ncccc=', 'Arelium'),
  (1, E'HHHH^\nH+H^^\nH|^^^', 'Dortlewall'),
  (1, E'y+cc.\nyyccy\nyyyyy', 'Newbie Village'),
  (1, E'.fyf.\nfffff\nyfff.', 'Mountaineer cottage'),
  (1, E'~~SSS\n~SSSc\n~Szcc', 'Laenor fort'),
  (1, E'sssss\nss?ss\nsssss', 'Woodhelven'),
  (1, E'^^^hs\n^^?hh\n^wrrh', 'Revelstone'),
  (1, E'hhhhs\nhh?hs\nhhhhs', 'Seance''s platform'),
  (1, E's^^^w\nss?hh\ns^^^^', 'Guards gap'),
  (1, E'rhhhh\nrr?hs\nhrrrs', 'Mithil'),
  (1, E'sssrs\nss?rr\nssrrs', 'Fouls creche'),
  (1, E'fFFFF\nfF?Ff\nffFff', 'Elven village'),
  (1, E'FFFFF\nfF?ff\nfffff', 'Dunedains dark mansion'),
  (1, E'fFFFF\nFf?ff\nffHfH', 'The Slopes of the Blackteeth Mountains'),
  (1, E'FFFFF\nFF?FF\nFFFFF', 'Elements'),
  (1, E'^^^^^\n^^?H^\n^HH^H', 'Gauntlet event'),
  (1, E'FFFFF\nFF?FF\nFFFFF', 'Forest of Legolas'),
  (1, E'FFFFF\nFF?ff\nfffff', 'Abandoned Valley'),
  (1, E'yyyyy\nyf?,,\nyyyyy', 'Pluras castle'),
  (1, E'.####\nf#?##\n.#f#f', 'Shrine'),
  (1, E'.....\n..?..\n.....', 'White marble tower'),
  (1, E'fffff\nff?ff\nfffff', 'Temple of Sarku'),
  (1, E'.....\n..!..\n.....', 'Monthy Python, Quest for the Holy Grail'),
  (1, E'HHH^^\nHH?^^\nH^^^^', 'Castle of Goddess'),
  (1, E'^^^^^\n^^HHH\n^HH^H', 'Temple to the Winds'),
  (1, E'ff,ff\nff?ff\nfffff', 'Chateau de le Bigeaul'),
  (1, E'fffff\nfFFFf\nFFFFf', 'Oakvale'),
  (1, E'ff,ff\n..?ff\n.....', 'Circus'),
  (1, E'fffff\nll?f/\nfff+f', 'Hugoville and von Huber'),
  (1, E'ffff.\n.f?ff\n..fff', 'Orc scouts treehouse'),
  (1, E'f...h\n,,?hh\n..hhh', 'Drawbridge'),
  (1, E'fFff.\nFF?ff\nFFFff', 'Newbie Forest'),
  (1, E'HH^^H\nHH?^^\n^HH^H', 'Raven, newbie mountain, trolls etc'),
  (1, E'H^^^^\nHH?^^\n^^^^^', 'Newbie Mountain'),
  (1, E'fffyy\nyffyy\nyyyy/', 'Wibble'),
  (1, E'fffyy\nyy?fy\nyyyyy', 'Petting Zoo'),
  (1, E'yfyyy\nyfyyy\nyfyyy', 'Arelium dungeons'),
  (1, E'^^H^H\nH^H^H\nH^^HH', 'Newbie Mines'),
  (1, E'ryyy+\nyy?y.\nyyyy.', 'Newbie park'),
  (1, E'^^HHH\n^^?HH\n^^HHH', 'Damned convent'),
  (1, E'yyyyy\nyy?yy\nyyffy', 'Bob and thelmas farm/grove'),
  (1, E'yyyyy\nyy?.y\nyy..y', 'Newbie playgrounds'),
  (1, E'yyFyy\n-----\nyyyyy', 'Nasu area'),
  (1, E'HHhhH\n^^?hh\n,,,,,', 'The Riddle of the Colours'),
  (1, E'.....\n..?..\n\\....', 'Newbie Playground'),
  (1, E'fFFFF\n,,?FF\nfffFF', 'Peacock Farm'),
  (1, E'FFFFF\nFF?Ff\nFFFFf', 'Foxhunt'),
  (1, E'../..\n-+?FF\nFFFFF', 'Merchant subguild'),
  (1, E',^^^^\nH,?^^\nH,HHH', 'Therps castle'),
  (1, E'yyyyy\nyy?yy\nyy,yy', 'Farm'),
  (1, E'FfffF\nFF?ff\nFFFff', 'Cathedral of Dr. Kilrathi'),
  (1, E'FFFFF\nFF?FF\nFFFFF', 'Alchemist Tower / Amazons'),
  (1, E'FFFFF\nfF?FF\nFFFFF', 'Alchemist Tower / Amazons, entrance 2'),
  (1, E'H^^^^\nHH?HH\nHHHHH', 'Darkcastle'),
  (1, E'hh#hh\nhh?##\nh###h', 'Chessboard'),
  (1, E'FFyyF\nFy?Ff\nFFFff', 'Gnomish flying machine'),
  (1, E'...ff\n..?Ff\nfFFff', 'Tower of the accursed'),
  (1, E'!^!^!\n!^?^!\n^^H^!', 'LAE-UNKNOWN '),
  (1, E'hhfrh\nhh?rh\nfffrr', 'Zoy''s Inn'),
  (1, E'!!^^h\n!^?hh\n^hhhh', 'Nun Temple'),
  (1, E'f,FFF\nff?FF\nfffFF', 'Secladin'),
  (1, E'~SS~~\n~SbS~\n~SSS~', 'Faerie Island'),
  (1, E'^^^^H\n^^fHh\nHhhHH', 'Faerie island'),
  (1, E'^HHHH\n^^sHH\n^^^^^', 'Caverns of the Undying'),
  (1, E'.....\nff...\nfffff', 'Asylum'),
  (1, E'yyyyy\nyy...\nyy...', 'Enchanter (quest)'),
  (1, E'ffff.\n.fff.\nffff.', 'Enchanter (corpse)'),
  (1, E'HH^^^\nHHv^^\nHHHH^', 'Mountain Dwarves'),
  (1, E'FFFFF\nFFFFF\nFFFFF', 'Faerie Forest'),
  (1, E'FFFFF\nFFFFF\nFFFFF', 'Small Meadow'),
  (1, E'h##H^\n#HH#H\nH##hH', 'Ix''ixixiblat'),
  (1, E'hffff\nfffff\nfffff', 'Kender Mansion'),
  (1, E'fffff\nfffff\nfffff', 'School of Lumine'),
  (1, E'.Ffff\nFFFff\nfFfff', 'Old Oak Forest'),
  (1, E'ff..f\nff.f.\nff...', 'Conifer Forest'),
  (1, E'hhhhh\n^^hhh\n^!^^^', 'Beastlands'),
  (1, E'fff,f\nfffff\nfffff', 'Stouby'),
  (1, E'fff|.\nffF|.\nfff+f', 'Wihne+ ss'),
  (1, E'^H|HH\n^^cc^\n^cccc', 'Tyr Farwyn'),
  (1, E'Szzzz\nzz...\nz..,,', 'Landfall'),
  (1, E'fffff\n.ffff\nfffff', 'Granny''s house'),
  (1, E'FFFFF\nFFFFF\nFFFFF', 'Wrebie forest'),
  (1, E'HHH^^\nH^H^^\n^H^^^', 'Bunny valley'),
  (1, E'....,\n...,.\n...,.', 'Lonely Inn'),
  (1, E'ffFff\nfffFf\n.ffFf', 'Butterfly farm'),
  (1, E'fffff\nfffff\nfffff', 'Mesme'),
  (1, E'fFFff\nfffff\nfffff', 'Forest of Moonrind'),
  (1, E'HH|HH\n^^?^^\n^^^^^', 'Iron mine'),
  (1, E'^^^^^\n^^?^^\nHH|HH', 'Iron mine (south entrance)'),
  (1, E'.##zz\n####z\n.,#zz', 'Sewers of Silverfang'),
  (1, E'SzSzz\nzzcc-\n..cc.', 'Vendace Shore'),
  (1, E'yyyyy\nyyyyy\nyyy+-', 'Fulgurite shop'),
  (1, E'H^^^^\nHH?^^\nHHHHH', 'Runemages guild northern entrance.'),
  (1, E'^^^^H\n^^?^H\n^^HHH', 'Runemages guild, the eastern entrance.'),
  (1, E'H^^H^\n^^?HH\nH^^^H', 'Runemages guild, western entrance.'),
  (1, E'HHHHH\n^^?^^\n^^^^H', 'Tarmalen summer guild'),
  (1, E'....z\n..?..\n----+', 'Squire guild'),
  (1, E'zzSSS\n.z?SS\n./zzS', 'Shipyard'),
  (1, E'^H^^^\nH^?^^\nH^H^^', 'Channelers'),
  (1, E'.+--=\n.|?.r\n.|..r', 'Knight guild'),
  (1, E'^^^^H\n^^?H^\n^^^^^', 'Ranger guild'),
  (1, E'FFFFl\nFF?Fl\nFFFFl', 'Druids'),
  (1, E'^^hh#\nhh%##\nh^###', 'Mage magical'),
  (1, E'RcccR\nRcccR\nRcccR', 'Crimson'),
  (1, E'..zzS\n...zS\n..zzS', 'Bruce''s shack'),
  (1, E'ycccy\nycccy\nycccy', 'Archer'),
  (1, E'fffff\n...ff\n...ff', 'Martial arts trainer (kobold)'),
  (1, E'HH^^H\n^^HHH\n^HHHH', 'Barb (lae)'),
  (1, E'sss..\nsssss\nsssss', 'Priest (lae)'),
  (1, E'ffrrf\nffrrf\nffrff', 'River cavalier'),
  (1, E'zzf.|\n....|\n....+', 'Suicidal+ ss'),
  (2, E'cccc^\ncccc^\ncccc^', 'Shadowkeep'),
  (2, E'~~SSS\n~~?zz\n~f,zz', 'Shadowkeep annex'),
  (2, E'f^^!^\ny^h^^\ny^^h^', 'Tower of Horn-Durath'),
  (2, E't^!^t\n^!?t^\nt^^^^', 'Frost giants'),
  (2, E'^^h^^\n^^?^^\n^^^^^', 'Lonely Mountain'),
  (2, E'ttttt\ntt?ht\nttttt', 'Dino''s taiga'),
  (2, E'^^^^^\nhh?^^\nhhhh^', 'Hells dojo'),
  (2, E'^^^^^\n^^?^^\n^^t^^', 'Frozen city of Rendburg'),
  (2, E'hhhht\nhh?hh\nhhhhh', 'Hill giants'),
  (2, E'ffffh\nff?Fh\nffFhF', 'Kalevala'),
  (2, E'fffff\nff?ff\nfffff', 'Abandoned study'),
  (2, E'fffff\nff?ff\nfffff', 'Cevi village'),
  (2, E'H####\nff?##\nff,ff', 'Barb guild event area'),
  (2, E'fffff\nff?ff\n-----', 'Campsite'),
  (2, E'h^^hh\nhh?hF\nFhhhF', 'Snowy peak'),
  (2, E'yyyyy\nyy?yy\nyyyyy', 'Knights & Dragons'),
  (2, E's##s#\ns#?#f\ns#fff', 'Dark Forest'),
  (2, E'fffff\nff?ff\nfffff', 'Stonehenge'),
  (2, E'.fffF\n.,?FF\n,fFFF', 'Mirkhold'),
  (2, E'^^^^^\n^^?vv\n^^^^v', 'Caverns of Chaos'),
  (2, E'yy^^y\nff?ff\nfffff', 'Smurville'),
  (2, E'HHH^^\n^^fHr\n^^HHr', 'Nun guild mountain entrance'),
  (2, E'^^ff^\n^^?^^\n^^^^^', 'Kathvael forest'),
  (2, E'^^^^h\n^^^hh\n^^^hh', 'Mountains'),
  (2, E'^^^^^\n^^?^H\nHHHHH', 'Ackbar''s warrior shrine'),
  (2, E'ss,,,\nss?ss\nhhhhh', 'Paupers castle'),
  (2, E'FFFFF\nFF?FF\nFFFFF', 'Old forest'),
  (2, E'vvvvF\nvv?--\nvFFFv', 'Amberley mansion'),
  (2, E'fff~~\n--?S~\nfffff', 'Donaru'),
  (2, E'fffff\n-+?ff\nff\\ff', 'Inn of the Four Winds'),
  (2, E'ffff^\nff?ff\nfffff', 'Perilous forest'),
  (2, E'.....\n..?..\n....S', 'Doobies'),
  (2, E'Hz~~~\n,,?~~\n~HHH~', 'Lighthouse'),
  (2, E'^^^^v\n^^?fv\n^^^^f', 'Mountainpass+citadel'),
  (2, E'hh^^^\nHhf^^\nHHhh^', 'Inra'),
  (2, E'SffSS\nfh.fS\nh^hff', 'Dark church, savage coast subarea'),
  (2, E'hhhhf\nhhihh\nhhhhh', 'Harazam, savage coast subarea'),
  (2, E'fffff\nffyff\nffff,', 'Wormhole, savage coast subarea'),
  (2, E'rffvv\nrvffv\nrfffv', 'Creepy forest, savage coast subarea'),
  (2, E'sssss\nsssss\nsssss', 'Mushroom hill'),
  (2, E't###h\n###hh\nh##hh', 'Ruins of untar trinit, savage coast subarea'),
  (2, E'hhhSS\nhhhSS\nhhffS', 'Norse village'),
  (2, E'^^^^f\n^^hff\n^^^^^', 'Stonetrolls'),
  (2, E'vvvvr\nvvvvr\nvvvvr', 'Spider cave, savage coast subarea'),
  (2, E'hhhhh\nhhhhh\nhhhhh', 'Old ladys shack, savage coast subarea'),
  (2, E'ff/^^\nf/v^^\n/^^^^', 'Swe+ ss'),
  (2, E'vvvvv\nvvvvv\nvvvvv', 'Hq1, warzone subarea'),
  (2, E'vvvvv\nvvvvv\nvvvvv', 'Camp1, warzone subarea'),
  (2, E'vvvvv\nvvvvv\nvvvvv', 'Warzone area'),
  (2, E'vvvvv\nvvvvv\nvvvvv', 'Camp2, warzone subarea'),
  (2, E'vvvvv\nvvvvv\nvvvvv', 'Hq2, warzone subarea'),
  (2, E'Fhrrr\nFFFrr\nFFFFr', 'Aldors village'),
  (2, E'hhh^^\nhhh^^\nhh^^h', 'Marble Shrine(?)'),
  (2, E'fffff\nfffff\nfffff', 'Attic'),
  (2, E'f###f\nf###f\nf###f', 'Ruins'),
  (2, E'h^^^^\nh^hh^\nhhh^^', 'Psi quest area'),
  (2, E'tHHHH\nHHttt\nHtttt', 'Trader''s House'),
  (2, E'fffff\nff.ff\nfffff', 'Moongate'),
  (2, E'~~~~~\n~~~~~\n~~~~~', 'ROTH-UNKNOWN '),
  (2, E'^^^^h\nhhhhh\nhhhhh', 'Old Copper Mine'),
  (2, E'HHH^^\nHHH^^\nHHH^^', 'Hack'),
  (2, E'iiiii\niiiii\niiiii', 'Plateau of tsang'),
  (2, E'fffff\nfffff\nff|ff', 'Beaumont Hamel'),
  (2, E'HHhhh\nHhh^^\nhh^^h', 'Evil vale'),
  (2, E'rFFsF\nFFFFs\nFFFFF', 'Severus castle'),
  (2, E'HHHHH\nHHHvv\nHHvvh', 'Ranger (roth)'),
  (2, E'rrrrr\nsssss\nsssss', 'Priest (roth)'),
  (2, E'~~~~~\n~~h~~\n~~hhh', 'Skyrider cavalier'),
  (2, E'frrff\nfffff\nfffff', 'Martial arts trainer (gnoll)'),
  (2, E'h^^^h\n^^?hh\n^hhhh', 'Tarmalen winter guild'),
  (2, E'^^^^h\nhh?^^\nhhhhh', 'Beastmaster guild'),
  (2, E'HHHHh\nHH?hh\nH,hhh', 'Barb guild'),
  (2, E'v^^^^\nvv?^^\n^vv^^', 'Nun guild'),
  (2, E'^^^^!\n^^?!!\n^!!^^', 'Navigator guild'),
  (2, E'~~vvv\n~~?--\n~~vvv', 'Psionicist guild'),
  (2, E'^^ii^\n^t%^^\ntt^^^', 'Mage cold'),
  (2, E'Hhh^^\nhh%^^\nh^^^^', 'Mage asphyxiation'),
  (2, E'HHFFF\nHHFFF\nHHFFF', 'Tiger shrine (roth)'),
  (2, E'HHHhh\nvvvvv\nvvvvv', 'The Hall of One Thousand Voices'),
  (2, E'HHHHH\nHHHHH\nHsHHH', 'Riftwalker shaman cave'),
  (2, E'SShhS\nSh.hS\nShhSS', 'Crimson wyrm, savage coast subarea'),
  (2, E'ffhhf\nfhhhh\nhhhih', 'Green wyrm, savage coast subarea'),
  (2, E'fhffS\nffbSS\nfffSS', 'Blue wyrm, savage coast subarea'),
  (2, E'^^fff\n^^hff\n^^^ff', 'Goathead, savage coast subarea'),
  (2, E'ffffh\nffhff\nfffff', 'Redhawk, savage coast subarea'),
  (2, E'^^vfr\n^^hfr\n^^ffr', 'Wyrms, savage coast subarea'),
  (3, E'Scccr\n~ccc-\n~c~Sr', 'Lorenchia'),
  (3, E'^^ddd\n^^d^d\n^^v^^', 'Valley of the Kings'),
  (3, E'~~~~~\n~y?yy\nyy|yy', 'Lucentium welcome center'),
  (3, E'ddddd\ndd?dd\nddddd', 'The Lost Pyramid'),
  (3, E'r=rr~\nr+?yy\n/fffy', 'Lands or lore'),
  (3, E'....d\n..?.d\nr....', 'Obelisk'),
  (3, E'fy/yy\ny/yyf\n/yyyy', 'Cornfield'),
  (3, E'ddd~~\n,,d~~\nddd~~', 'Lanzia'),
  (3, E'ddddd\n,,ddd\ndddd.', 'Colosseum'),
  (3, E'ffff,\nff,f,\nff,f,', 'Dahbec'),
  (3, E'yyffy\nfyyff\nyfyyy', 'Beanstalk'),
  (3, E'.ll.d\nlll.d\n.l..d', 'Oasis'),
  (3, E'yyy,f\nffyff\nyyyyy', 'Village of Shrea'),
  (3, E'ddddd\nddddd\nddddd', 'Nifties'),
  (3, E'f^^~~\n,,^f~\nfbbb~', 'Stagira'),
  (3, E'jFjFF\nFFjF.\n..,..', 'The Ruins of Astacia'),
  (3, E'rffff\nrffff\nrffff', 'Public Gardens'),
  (3, E'fhhhh\nffhhh\nfffyh', 'The Trilloch tower'),
  (3, E'fffff\nfffff\n....,', 'Anthill'),
  (3, E'ffffS\n--fSS\nfffff', 'Paladin Stronghold'),
  (3, E'FFFFF\nFFFFF\nFF+--', 'Tree village'),
  (3, E'~~SS~\n~SS~~\n~~~~S', 'Sunken ship'),
  (3, E'b..b~\nb..h~\nbhhh~', 'Giants/rechendak'),
  (3, E'bbbFF\nbbbFF\nFFFFF', 'Fraggle village'),
  (3, E'^^hhh\n^^h--\n^^hhh', 'Duzelton'),
  (3, E'~jrjy\njj~ry\njjjrj', 'Whirlpool'),
  (3, E'hh,yy\nhh,,y\nfhf,y', 'Land of the Overworld'),
  (3, E'..bSS\n..bbS\n...bS', 'Beach'),
  (3, E'.hhh^\nhhh^^\nhh^^^', 'Stifsim'),
  (3, E'SS~~S\nS~~~S\nS~~SS', 'Oystria'),
  (3, E'~~~~~\n~~c~~\n~~~~~', 'Silver lake'),
  (3, E'^^^^^\n~~^hh\n~~hhh', 'Karatur'),
  (3, E'sssss\nsssss\nsssss', 'Troglodytes'),
  (3, E'sssss\nsssss\nsssss', 'Steves hut, Troglodyte subarea'),
  (3, E'^^^^^\n^^^h^\n^^hhh', 'Mirror Mine'),
  (3, E'FFFFF\nFFvFF\nFFFFF', 'Earthquake event'),
  (3, E'FFFFF\nFFFFF\nFFFFF', 'Hailstorm event'),
  (3, E'FFFFF\nFFFFF\nFFFFF', 'Meteor shower event'),
  (3, E'FFFFF\nFFFFF\nFFFFF', 'Cyclone event tower'),
  (3, E'jjjjR\njjjjj\njjjjj', 'Pyran'),
  (3, E'h###j\n####j\nh###j', 'Adamantium chain'),
  (3, E'hhh^^\nhhd^^\nhh^^^', 'Templar shield quest cave'),
  (3, E'SSSSS\nbb~SS\nybbbS', 'Navigators of the sea'),
  (3, E'FFFF#\nFFFF#\nFFFFF', 'Old house'),
  (3, E'ddddd\nddddd\nddddd', 'Village of War'),
  (3, E'l.ddd\n...dd\nddddd', 'Village of Famine'),
  (3, E'ddddd\nddddd\nddddd', 'Village of Pestilence'),
  (3, E'ddddd\nddddd\nddddd', 'Village of Death'),
  (3, E'bbjbb\nSbbbS\nSSSSS', 'Clockwork observatory'),
  (3, E'.....\n..j..\n.....', 'Kirahvi+ ss'),
  (3, E'h^^^^\nhhh^^\nhhhh^', 'Underdark'),
  (3, E'SSSSS\nSSbbb\nSbfff', 'Satyr forest'),
  (3, E'fffff\nfffff\nffffH', 'A Tale of Two Towers'),
  (3, E'bbjjj\nSbbjj\nSSSSS', 'Catfolk shipyard'),
  (3, E'yyfff\nyyfff\nfyfff', 'Efiilas advance camp'),
  (3, E'fffff\nfffff\nfffff', 'Coffee forest'),
  (3, E'hhhhh\nh^hhh\n^^^^^', 'Draconian tower'),
  (3, E'hhh^^\nhhh^^\nhh^^^', 'Dwarf warehouse'),
  (3, E'ddddb\nddddb\nddddd', 'Gladiator training grounds'),
  (3, E'bjjbS\nbjjjb\nbbjjb', 'Ruins of Kofgaad'),
  (3, E'lfffl\nlffff\nlllfl', 'Monks'),
  (3, E'fffff\nfffff\nfffff', 'Alchemist guild'),
  (3, E'hhhdd\n^hhdd\n^dddd', 'Tarmalen autumn guild'),
  (3, E'jjjjj\njjjjj\njjjjj', 'Mage poison'),
  (3, E'~j^^^\n~~^V^\n~jj^b', 'Mage guild, electricity'),
  (3, E'jjjjj\njjjjj\njssjj', 'Tiger shrine (luce)'),
  (3, E'jjjjj\nj^#^j\njjjj^', 'Temple of Tzarakk'),
  (3, E'srjjj\nsrjjj\n~~~~~', 'Martial arts trainer (catfolk)'),
  (3, E'bSSSS\n.bbSS\n....S', 'Ranger (luc)'),
  (3, E'hhhh^\n^^hhh\nrrrrh', 'Barb (luc)'),
  (3, E'sssss\nsssss\nsssss', 'Priest (luc)'),
  (3, E'FFFrR\njjjrR\njjjrR', 'Jungle cavalier'),
  (4, E'hhh^^\n^^h^^\n^^^^^', 'Aljerak temple'),
  (4, E'^cccc\n=cccc\n^cccc', 'Rilynt''tar'),
  (4, E'~~SSF\n~~?SF\n~~|SF', 'Ril''ynttar harbour'),
  (4, E'FsFF~\nhh?F~\nsFss~', 'Elven Outpost'),
  (4, E'~~FFF\n~~?FF\n~~~FF', 'Manor'),
  (4, E'HHFFs\nFF?FF\nFFFsF', 'Samurai fort'),
  (4, E'ss~~~\nyy?S~\nyyyS~', 'Domgroth''s Mansion'),
  (4, E'sFFFF\nsF?FF\nFFFF/', 'Haunted Mansion'),
  (4, E'xxLL^\n^^?VL\n^^^L^', 'Volcano'),
  (4, E'@xxHH\n@^?HH\nV^^HH', 'Golem'),
  (4, E'FFFFF\nFF?FF\nFFFFF', 'Darkwood'),
  (4, E'^^^^^\nH^?^^\nHHH\\-', 'Brantis'),
  (4, E'####x\n##?#x\nx#xxx', 'Perins'),
  (4, E'FFxxx\nxx?xx\nxxFFx', 'Mansion'),
  (4, E'^^^^^\nhh?^^\n^hh^^', 'Tiamat'),
  (4, E'FxxFF\nFF?FF\nFFFFF', 'Temple of the Twisted Prophecies'),
  (4, E'hhhhh\nhh?,,\n^hhhh', 'Orthanc'),
  (4, E'hh^^^\n^h?^^\n^hh^^', 'Kutanakor, west entrance'),
  (4, E'^^hh^\n^^?h^\n^^^h^', 'Kutanakor, east entrance'),
  (4, E'^FFFF\nFF?FF\nFFFFh', 'Ikar'),
  (4, E'^^^hh\n!^?hh\n^^hhL', 'Hell'),
  (4, E'sss^^\n~s?^^\n~~~~^', 'An old fort'),
  (4, E'^^#^^\n^#?#^\n^hh^^', 'Tower of Corabandor'),
  (4, E'hVVVh\nVV?VV\nxxLLL', 'Fire giants'),
  (4, E'jjjjj\njj?jj\njjjjj', 'Ndoki'),
  (4, E'jjjjj\njj?jj\njjjjj', 'Cavemen'),
  (4, E'#h##b\n##?#b\n###bb', 'Atlantis'),
  (4, E'sFFFs\nFs?FF\nss,sF', 'Necromancer'),
  (4, E'FFFFF\nFs?FF\nFsFFF', 'Forest of the Moon'),
  (4, E'LLxxx\nLLxxx\nLLLxx', 'Castle Firefox'),
  (4, E'H^^^H\nx^L^H\n@@V^H', 'Citadel pit'),
  (4, E'hhhhh\n^^hhh\n^^^^h', 'Wanderer maze'),
  (4, E'sssss\nFFfss\nFsFFF', 'Abandoned house'),
  (4, E'SSjss\nrsjjj\nrsjjs', 'Trillazoo'),
  (4, E'sssss\nsssss\nsssss', 'Zonni swamps'),
  (4, E'^^jjj\n^^jjj\n^^^jj', 'Savage jungle'),
  (4, E'^^^^^\nHH?^^\nHHH^^', 'Cartwheel'),
  (4, E'FFFFF\n,,FFF\nFFFFF', 'Plakhstan'),
  (4, E',##ss\n,###s\n,##ss', 'Temple of Chaos'),
  (4, E'~~~ss\n~~sss\n~~~ss', 'Furnachia fort (west)'),
  (4, E'ssSSS\nsssSS\nsssSS', 'Furnachia fort (east)'),
  (4, E'jjj~~\n~~j~~\n~~~~~', 'Furnachia fort (south)'),
  (4, E'ss+--\ns/FsF\n/sFFF', 'Abandoned village'),
  (4, E'hhh^^\nhhh^^\nh^^^^', 'Mountain peak'),
  (4, E'FFF#F\n#F#FF\nFFFFF', 'Abandoned, ruined temple'),
  (4, E'slH^H\nll#^^\nl^^^^', 'Drow tower'),
  (4, E'^^#LV\n^^##L\n^#^##', 'Priest guild special place'),
  (4, E'sshs~\nhhhh~\nsh^h~', 'Infection'),
  (4, E'FFFFH\nFFFFF\nFFFFH', 'Monk (furn)'),
  (4, E'HFFFF\nHHFFF\nH^HFF', 'Ranger (furn)'),
  (4, E'HH^^H\nHHH^H\nHHH^H', 'Barb (furn)'),
  (4, E'^^^^^\n^^hhh\nhhhhh', 'Martial arts trainer (dwarf)'),
  (4, E'HHHFF\nHH?FF\nHH^HF', 'Lords of chaos'),
  (4, E'^^^^^\n^^?^^\nLL^^^', 'Wanderer''s guild'),
  (4, E'hhVLL\nLh%hL\nxxhLL', 'Mage fire'),
  (4, E'xxxxx\nxxxxx\nxxxxx', 'Badlands cavalier'),
  (5, E'^RcR^\nRcccR\n^RcR^', 'Calythien'),
  (5, E'HH~~~\n--?~~\nHHH~~', 'Windham'),
  (5, E'SSSSS\nSS?SS\nh,hhh', 'Seashore Tower'),
  (5, E'hFhhF\nFh?hh\n,,,,,', 'Dunamor'),
  (5, E'SSSSS\nhh?SS\n,,,hh', 'West wharf'),
  (5, E'~~~HH\n~~?HH\n~~v\\H', 'Sunderland'),
  (5, E'FHFHF\nFF?FF\nFFFFF', 'The Last Unicorn'),
  (5, E'..F.F\n.F?FF\n...F.', 'Teywaer Graveyard'),
  (5, E'h^^hh\n^^?Fh\n^FFFh', 'Teywaer Tunnel'),
  (5, E'FFFFF\nFF?FF\nFFFFF', 'Teywaer village'),
  (5, E'..F..\n.Ff..\n.FF.F', 'Teywaer well'),
  (5, E'^^^^^\n^^?^^\nvvv^^', 'Celestial Caverns'),
  (5, E'S...S\nSF..S\nh..SS', 'Goblin citadel'),
  (5, E'FFFFF\nFF?FF\nFFFFF', 'Well'),
  (5, E'rRvvv\nrR?vv\nrRrvv', 'Twisted tower'),
  (5, E'zh^^h\nh^?##\nzh##h', 'Cathedral'),
  (5, E'#####\n##?#l\n####l', 'Ruins of El Deagnoh'),
  (5, E'#^^^^\n#^?^^\n###^^', 'Halls of the Dead'),
  (5, E'^^^^v\n^^?vv\n^^vvv', 'Kobold mines'),
  (5, E'vvvvH\nvv?vv\nvvvvv', 'Tiburico'),
  (5, E'vvvvv\n^^?^^\n^^^^^', 'Castle of Toxic'),
  (5, E'h|h.S\nh+?.S\nhh\\.S', 'Seabird Inn'),
  (5, E'^^^HH\n^^?HH\n^^HHH', '51 daughters'),
  (5, E'^^^^^\nHH?^H\nsHHHH', 'The valley of silence'),
  (5, E'ff^^^\n--?^^\nHff^^', 'Tralpecktor'),
  (5, E'dddd^\ndd?dd\nddddd', 'The Ancient Temple of the Gods'),
  (5, E'~##..\n##?#h\n~##f.', 'Stone garden'),
  (5, E'^HHHH\n^^?HH\n^^^^^', 'The Warlock Conclave'),
  (5, E'ddddd\ndd?dd\nddddd', 'Tarackia'),
  (5, E'fffff\nff?fv\nff,ff', 'Brimshire'),
  (5, E'fffHv\nff?vv\nffvvv', 'Soy'),
  (5, E'fffff\nff?ff\nsffff', 'Hairikko Forest'),
  (5, E'vvvvv\nvv?vv\nvv|vv', 'The Temple of Pandion Knights'),
  (5, E'Hvvvv\nvv?vH\nvvvvH', 'Villager under attack'),
  (5, E'HH#HH\nH#?#H\nHH#HH', 'Ochimo'),
  (5, E'hhhhh\nsh?hS\nsh~SS', 'Red Tides'),
  (5, E'H^^^^\nHH?^^\nHH^^^', 'Caves of Orac'),
  (5, E'HH#H#\n##?#,\nv##HH', 'Ruins of a Temple of All Gods'),
  (5, E'####H\nH#?#H\nH####', 'DESO-UNKNOWN '),
  (5, E'fsfss\nff?ss\nffHsf', 'Goblin Farm'),
  (5, E'fvHHH\nfv?Hf\nvvvHf', 'Mythical Valley'),
  (5, E'sssss\nsfsss\nffffs', 'Millie''s Nightmare'),
  (5, E'HyyFF\nHy?FF\nHH,Fl', 'Buckthorn Valley'),
  (5, E'fffff\nfffff\nfffff', 'The Lands of Apollo'),
  (5, E'^^^^~\n^^^^^\n^^svv', 'Magerathia'),
  (5, E'HH^^^\n...^^\n...^^', 'Tinmen Monastery'),
  (5, E'vvvvv\nvvvvv\nvvvvv', 'Abandoned barn'),
  (5, E'...ff\n.hhhf\nhhhhh', 'Snotling farm'),
  (5, E'^^^vv\n^^vvv\n^^vrr', 'Zorn'),
  (5, E'hhhhh\nhhhhh\nhhhhh', 'Feldspar conglomerate'),
  (5, E'vHHHH\nvvHHH\nvvvHH', 'Meadowshire'),
  (5, E'.....\n..,F.\nS,,.,', 'Broken Forest - Castle'),
  (5, E'S..,F\nSS,,.\n==,,,', 'Broken Forest - Barracks'),
  (5, E',.,.S\n,,,SS\nSSSSS', 'Broken Forest - Seacrest'),
  (5, E'...SS\nF.,SS\n.,.SS', 'Broken Forest - Prison'),
  (5, E'HHHHH\nHHHHH\nHHHHH', 'Ranger (deso)'),
  (5, E'HHH^^\n^^HH^\n^^^H^', 'Barb (deso)'),
  (5, E'sslls\nsssls\nsssss', 'Priest (deso)'),
  (5, E'HH#HH\nz###H\nHH#HH', 'Midnight cavalier'),
  (5, E'hssss\nhs%ss\nhssss', 'Mage acid'),
  (5, E'vv,^^\n^^?^^\n^^^^^', 'Templar guild'),
  (5, E'sssss\nss?sH\nsssss', 'Tarmalen spring guild'),
  (5, E'^^hhh\n^^?hh\n^^^hh', 'Conjurer guild'),
  (5, E'^dddH\ndd?#d\ndd##d', 'Reaver guild'),
  (5, E'HHH##\nHHH##\nHH###', 'Tiger shrine (deso)'),
  (5, E'^^^^d\nd^ddd\nddddd', 'Aelena temple'),
  (5, E'/FFFF\nFFFFF\nFFFFF', 'Ghost liberator mansion'),
  (5, E'fffff\nfffff\nfffff', 'Animist guild'),
  (5, E'fffff\nfffff\nfffff', 'The Navigators of the Tree');
