INSERT INTO tags (taggroup_id, map, name) VALUES
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'zczcR\nccccR\ncccc=', 'Arelium'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'HHHH^\nH+H^^\nH|^^^', 'Dortlewall'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'y+cc.\nyyccy\nyyyyy', 'Newbie Village'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'.fyf.\nfffff\nyfff.', 'Mountaineer cottage'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'~~SSS\n~SSSc\n~Szcc', 'Laenor fort'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'sssss\nss?ss\nsssss', 'Woodhelven'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^^^hs\n^^?hh\n^wrrh', 'Revelstone'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'hhhhs\nhh?hs\nhhhhs', 'Seance''s platform'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E's^^^w\nss?hh\ns^^^^', 'Guards gap'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'rhhhh\nrr?hs\nhrrrs', 'Mithil'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'sssrs\nss?rr\nssrrs', 'Fouls creche'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fFFFF\nfF?Ff\nffFff', 'Elven village'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFFFF\nfF?ff\nfffff', 'Dunedains dark mansion'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fFFFF\nFf?ff\nffHfH', 'The Slopes of the Blackteeth Mountains'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFFFF\nFF?FF\nFFFFF', 'Elements'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^^^^^\n^^?H^\n^HH^H', 'Gauntlet event'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFFFF\nFF?FF\nFFFFF', 'Forest of Legolas'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFFFF\nFF?ff\nfffff', 'Abandoned Valley'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'yyyyy\nyf?,,\nyyyyy', 'Pluras castle'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'.####\nf#?##\n.#f#f', 'Shrine'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'.....\n..?..\n.....', 'White marble tower'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fffff\nff?ff\nfffff', 'Temple of Sarku'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'.....\n..!..\n.....', 'Monthy Python, Quest for the Holy Grail'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'HHH^^\nHH?^^\nH^^^^', 'Castle of Goddess'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^^^^^\n^^HHH\n^HH^H', 'Temple to the Winds'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'ff,ff\nff?ff\nfffff', 'Chateau de le Bigeaul'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fffff\nfFFFf\nFFFFf', 'Oakvale'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'ff,ff\n..?ff\n.....', 'Circus'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fffff\nll?f/\nfff+f', 'Hugoville and von Huber'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'ffff.\n.f?ff\n..fff', 'Orc scouts treehouse'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'f...h\n,,?hh\n..hhh', 'Drawbridge'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fFff.\nFF?ff\nFFFff', 'Newbie Forest'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'HH^^H\nHH?^^\n^HH^H', 'Raven, newbie mountain, trolls etc'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'H^^^^\nHH?^^\n^^^^^', 'Newbie Mountain'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fffyy\nyffyy\nyyyy/', 'Wibble'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fffyy\nyy?fy\nyyyyy', 'Petting Zoo'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'yfyyy\nyfyyy\nyfyyy', 'Arelium dungeons'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^^H^H\nH^H^H\nH^^HH', 'Newbie Mines'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'ryyy+\nyy?y.\nyyyy.', 'Newbie park'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^^HHH\n^^?HH\n^^HHH', 'Damned convent'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'yyyyy\nyy?yy\nyyffy', 'Bob and thelmas farm/grove'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'yyyyy\nyy?.y\nyy..y', 'Newbie playgrounds'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'yyFyy\n-----\nyyyyy', 'Nasu area'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'HHhhH\n^^?hh\n,,,,,', 'The Riddle of the Colours'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'.....\n..?..\n\\....', 'Newbie Playground'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fFFFF\n,,?FF\nfffFF', 'Peacock Farm'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFFFF\nFF?Ff\nFFFFf', 'Foxhunt'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'../..\n-+?FF\nFFFFF', 'Merchant subguild'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E',^^^^\nH,?^^\nH,HHH', 'Therps castle'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'yyyyy\nyy?yy\nyy,yy', 'Farm'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FfffF\nFF?ff\nFFFff', 'Cathedral of Dr. Kilrathi'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFFFF\nFF?FF\nFFFFF', 'Alchemist Tower / Amazons'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFFFF\nfF?FF\nFFFFF', 'Alchemist Tower / Amazons, entrance 2'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'H^^^^\nHH?HH\nHHHHH', 'Darkcastle'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'hh#hh\nhh?##\nh###h', 'Chessboard'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFyyF\nFy?Ff\nFFFff', 'Gnomish flying machine'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'...ff\n..?Ff\nfFFff', 'Tower of the accursed'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'!^!^!\n!^?^!\n^^H^!', 'LAE-UNKNOWN '),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'hhfrh\nhh?rh\nfffrr', 'Zoy''s Inn'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'!!^^h\n!^?hh\n^hhhh', 'Nun Temple'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'f,FFF\nff?FF\nfffFF', 'Secladin'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'~SS~~\n~SbS~\n~SSS~', 'Faerie Island'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^^^^H\n^^fHh\nHhhHH', 'Faerie island'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^HHHH\n^^sHH\n^^^^^', 'Caverns of the Undying'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'.....\nff...\nfffff', 'Asylum'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'yyyyy\nyy...\nyy...', 'Enchanter (quest)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'ffff.\n.fff.\nffff.', 'Enchanter (corpse)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'HH^^^\nHHv^^\nHHHH^', 'Mountain Dwarves'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFFFF\nFFFFF\nFFFFF', 'Faerie Forest'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFFFF\nFFFFF\nFFFFF', 'Small Meadow'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'h##H^\n#HH#H\nH##hH', 'Ix''ixixiblat'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'hffff\nfffff\nfffff', 'Kender Mansion'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fffff\nfffff\nfffff', 'School of Lumine'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'.Ffff\nFFFff\nfFfff', 'Old Oak Forest'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'ff..f\nff.f.\nff...', 'Conifer Forest'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'hhhhh\n^^hhh\n^!^^^', 'Beastlands'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fff,f\nfffff\nfffff', 'Stouby'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fff|.\nffF|.\nfff+f', 'Wihne+ ss'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^H|HH\n^^cc^\n^cccc', 'Tyr Farwyn'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'Szzzz\nzz...\nz..,,', 'Landfall'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fffff\n.ffff\nfffff', 'Granny''s house'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFFFF\nFFFFF\nFFFFF', 'Wrebie forest'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'HHH^^\nH^H^^\n^H^^^', 'Bunny valley'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'....,\n...,.\n...,.', 'Lonely Inn'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'ffFff\nfffFf\n.ffFf', 'Butterfly farm'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fffff\nfffff\nfffff', 'Mesme'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fFFff\nfffff\nfffff', 'Forest of Moonrind'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'HH|HH\n^^?^^\n^^^^^', 'Iron mine'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^^^^^\n^^?^^\nHH|HH', 'Iron mine (south entrance)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'.##zz\n####z\n.,#zz', 'Sewers of Silverfang'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'SzSzz\nzzcc-\n..cc.', 'Vendace Shore'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'yyyyy\nyyyyy\nyyy+-', 'Fulgurite shop'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'H^^^^\nHH?^^\nHHHHH', 'Runemages guild northern entrance.'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^^^^H\n^^?^H\n^^HHH', 'Runemages guild, the eastern entrance.'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'H^^H^\n^^?HH\nH^^^H', 'Runemages guild, western entrance.'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'HHHHH\n^^?^^\n^^^^H', 'Tarmalen summer guild'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'....z\n..?..\n----+', 'Squire guild'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'zzSSS\n.z?SS\n./zzS', 'Shipyard'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^H^^^\nH^?^^\nH^H^^', 'Channelers'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'.+--=\n.|?.r\n.|..r', 'Knight guild'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^^^^H\n^^?H^\n^^^^^', 'Ranger guild'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'FFFFl\nFF?Fl\nFFFFl', 'Druids'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'^^hh#\nhh%##\nh^###', 'Mage magical'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'RcccR\nRcccR\nRcccR', 'Crimson'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'..zzS\n...zS\n..zzS', 'Bruce''s shack'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'ycccy\nycccy\nycccy', 'Archer'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'fffff\n...ff\n...ff', 'Martial arts trainer (kobold)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'HH^^H\n^^HHH\n^HHHH', 'Barb (lae)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'sss..\nsssss\nsssss', 'Priest (lae)'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'ffrrf\nffrrf\nffrff', 'River cavalier'),
  (uuid_generate_v5 (uuid_nil(), 'laenor'), E'zzf.|\n....|\n....+', 'Suicidal+ ss'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'cccc^\ncccc^\ncccc^', 'Shadowkeep'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'~~SSS\n~~?zz\n~f,zz', 'Shadowkeep annex'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'f^^!^\ny^h^^\ny^^h^', 'Tower of Horn-Durath'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E't^!^t\n^!?t^\nt^^^^', 'Frost giants'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^h^^\n^^?^^\n^^^^^', 'Lonely Mountain'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'ttttt\ntt?ht\nttttt', 'Dino''s taiga'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^^^^\nhh?^^\nhhhh^', 'Hells dojo'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^^^^\n^^?^^\n^^t^^', 'Frozen city of Rendburg'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'hhhht\nhh?hh\nhhhhh', 'Hill giants'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'ffffh\nff?Fh\nffFhF', 'Kalevala'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'fffff\nff?ff\nfffff', 'Abandoned study'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'fffff\nff?ff\nfffff', 'Cevi village'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'H####\nff?##\nff,ff', 'Barb guild event area'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'fffff\nff?ff\n-----', 'Campsite'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'h^^hh\nhh?hF\nFhhhF', 'Snowy peak'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'yyyyy\nyy?yy\nyyyyy', 'Knights & Dragons'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E's##s#\ns#?#f\ns#fff', 'Dark Forest'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'fffff\nff?ff\nfffff', 'Stonehenge'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'.fffF\n.,?FF\n,fFFF', 'Mirkhold'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^^^^\n^^?vv\n^^^^v', 'Caverns of Chaos'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'yy^^y\nff?ff\nfffff', 'Smurville'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'HHH^^\n^^fHr\n^^HHr', 'Nun guild mountain entrance'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^ff^\n^^?^^\n^^^^^', 'Kathvael forest'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^^^h\n^^^hh\n^^^hh', 'Mountains'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^^^^\n^^?^H\nHHHHH', 'Ackbar''s warrior shrine'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'ss,,,\nss?ss\nhhhhh', 'Paupers castle'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'FFFFF\nFF?FF\nFFFFF', 'Old forest'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'vvvvF\nvv?--\nvFFFv', 'Amberley mansion'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'fff~~\n--?S~\nfffff', 'Donaru'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'fffff\n-+?ff\nff\\ff', 'Inn of the Four Winds'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'ffff^\nff?ff\nfffff', 'Perilous forest'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'.....\n..?..\n....S', 'Doobies'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'Hz~~~\n,,?~~\n~HHH~', 'Lighthouse'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^^^v\n^^?fv\n^^^^f', 'Mountainpass+citadel'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'hh^^^\nHhf^^\nHHhh^', 'Inra'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'SffSS\nfh.fS\nh^hff', 'Dark church, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'hhhhf\nhhihh\nhhhhh', 'Harazam, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'fffff\nffyff\nffff,', 'Wormhole, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'rffvv\nrvffv\nrfffv', 'Creepy forest, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'sssss\nsssss\nsssss', 'Mushroom hill'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E't###h\n###hh\nh##hh', 'Ruins of untar trinit, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'hhhSS\nhhhSS\nhhffS', 'Norse village'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^^^f\n^^hff\n^^^^^', 'Stonetrolls'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'vvvvr\nvvvvr\nvvvvr', 'Spider cave, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'hhhhh\nhhhhh\nhhhhh', 'Old ladys shack, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'ff/^^\nf/v^^\n/^^^^', 'Swe+ ss'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'vvvvv\nvvvvv\nvvvvv', 'Hq1, warzone subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'vvvvv\nvvvvv\nvvvvv', 'Camp1, warzone subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'vvvvv\nvvvvv\nvvvvv', 'Warzone area'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'vvvvv\nvvvvv\nvvvvv', 'Camp2, warzone subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'vvvvv\nvvvvv\nvvvvv', 'Hq2, warzone subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'Fhrrr\nFFFrr\nFFFFr', 'Aldors village'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'hhh^^\nhhh^^\nhh^^h', 'Marble Shrine(?)'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'fffff\nfffff\nfffff', 'Attic'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'f###f\nf###f\nf###f', 'Ruins'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'h^^^^\nh^hh^\nhhh^^', 'Psi quest area'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'tHHHH\nHHttt\nHtttt', 'Trader''s House'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'fffff\nff.ff\nfffff', 'Moongate'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'~~~~~\n~~~~~\n~~~~~', 'ROTH-UNKNOWN '),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^^^h\nhhhhh\nhhhhh', 'Old Copper Mine'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'HHH^^\nHHH^^\nHHH^^', 'Hack'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'iiiii\niiiii\niiiii', 'Plateau of tsang'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'fffff\nfffff\nff|ff', 'Beaumont Hamel'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'HHhhh\nHhh^^\nhh^^h', 'Evil vale'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'rFFsF\nFFFFs\nFFFFF', 'Severus castle'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'HHHHH\nHHHvv\nHHvvh', 'Ranger (roth)'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'rrrrr\nsssss\nsssss', 'Priest (roth)'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'~~~~~\n~~h~~\n~~hhh', 'Skyrider cavalier'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'frrff\nfffff\nfffff', 'Martial arts trainer (gnoll)'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'h^^^h\n^^?hh\n^hhhh', 'Tarmalen winter guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^^^h\nhh?^^\nhhhhh', 'Beastmaster guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'HHHHh\nHH?hh\nH,hhh', 'Barb guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'v^^^^\nvv?^^\n^vv^^', 'Nun guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^^^!\n^^?!!\n^!!^^', 'Navigator guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'~~vvv\n~~?--\n~~vvv', 'Psionicist guild'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^ii^\n^t%^^\ntt^^^', 'Mage cold'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'Hhh^^\nhh%^^\nh^^^^', 'Mage asphyxiation'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'HHFFF\nHHFFF\nHHFFF', 'Tiger shrine (roth)'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'HHHhh\nvvvvv\nvvvvv', 'The Hall of One Thousand Voices'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'HHHHH\nHHHHH\nHsHHH', 'Riftwalker shaman cave'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'SShhS\nSh.hS\nShhSS', 'Crimson wyrm, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'ffhhf\nfhhhh\nhhhih', 'Green wyrm, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'fhffS\nffbSS\nfffSS', 'Blue wyrm, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^fff\n^^hff\n^^^ff', 'Goathead, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'ffffh\nffhff\nfffff', 'Redhawk, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'rothikgen'), E'^^vfr\n^^hfr\n^^ffr', 'Wyrms, savage coast subarea'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'Scccr\n~ccc-\n~c~Sr', 'Lorenchia'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'^^ddd\n^^d^d\n^^v^^', 'Valley of the Kings'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'~~~~~\n~y?yy\nyy|yy', 'Lucentium welcome center'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'ddddd\ndd?dd\nddddd', 'The Lost Pyramid'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'r=rr~\nr+?yy\n/fffy', 'Lands or lore'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'....d\n..?.d\nr....', 'Obelisk'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'fy/yy\ny/yyf\n/yyyy', 'Cornfield'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'ddd~~\n,,d~~\nddd~~', 'Lanzia'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'ddddd\n,,ddd\ndddd.', 'Colosseum'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'ffff,\nff,f,\nff,f,', 'Dahbec'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'yyffy\nfyyff\nyfyyy', 'Beanstalk'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'.ll.d\nlll.d\n.l..d', 'Oasis'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'yyy,f\nffyff\nyyyyy', 'Village of Shrea'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'ddddd\nddddd\nddddd', 'Nifties'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'f^^~~\n,,^f~\nfbbb~', 'Stagira'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'jFjFF\nFFjF.\n..,..', 'The Ruins of Astacia'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'rffff\nrffff\nrffff', 'Public Gardens'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'fhhhh\nffhhh\nfffyh', 'The Trilloch tower'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'fffff\nfffff\n....,', 'Anthill'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'ffffS\n--fSS\nfffff', 'Paladin Stronghold'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'FFFFF\nFFFFF\nFF+--', 'Tree village'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'~~SS~\n~SS~~\n~~~~S', 'Sunken ship'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'b..b~\nb..h~\nbhhh~', 'Giants/rechendak'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'bbbFF\nbbbFF\nFFFFF', 'Fraggle village'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'^^hhh\n^^h--\n^^hhh', 'Duzelton'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'~jrjy\njj~ry\njjjrj', 'Whirlpool'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'hh,yy\nhh,,y\nfhf,y', 'Land of the Overworld'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'..bSS\n..bbS\n...bS', 'Beach'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'.hhh^\nhhh^^\nhh^^^', 'Stifsim'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'SS~~S\nS~~~S\nS~~SS', 'Oystria'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'~~~~~\n~~c~~\n~~~~~', 'Silver lake'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'^^^^^\n~~^hh\n~~hhh', 'Karatur'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'sssss\nsssss\nsssss', 'Troglodytes'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'sssss\nsssss\nsssss', 'Steves hut, Troglodyte subarea'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'^^^^^\n^^^h^\n^^hhh', 'Mirror Mine'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'FFFFF\nFFvFF\nFFFFF', 'Earthquake event'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'FFFFF\nFFFFF\nFFFFF', 'Hailstorm event'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'FFFFF\nFFFFF\nFFFFF', 'Meteor shower event'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'FFFFF\nFFFFF\nFFFFF', 'Cyclone event tower'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'jjjjR\njjjjj\njjjjj', 'Pyran'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'h###j\n####j\nh###j', 'Adamantium chain'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'hhh^^\nhhd^^\nhh^^^', 'Templar shield quest cave'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'SSSSS\nbb~SS\nybbbS', 'Navigators of the sea'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'FFFF#\nFFFF#\nFFFFF', 'Old house'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'ddddd\nddddd\nddddd', 'Village of War'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'l.ddd\n...dd\nddddd', 'Village of Famine'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'ddddd\nddddd\nddddd', 'Village of Pestilence'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'ddddd\nddddd\nddddd', 'Village of Death'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'bbjbb\nSbbbS\nSSSSS', 'Clockwork observatory'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'.....\n..j..\n.....', 'Kirahvi+ ss'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'h^^^^\nhhh^^\nhhhh^', 'Underdark'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'SSSSS\nSSbbb\nSbfff', 'Satyr forest'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'fffff\nfffff\nffffH', 'A Tale of Two Towers'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'bbjjj\nSbbjj\nSSSSS', 'Catfolk shipyard'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'yyfff\nyyfff\nfyfff', 'Efiilas advance camp'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'fffff\nfffff\nfffff', 'Coffee forest'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'hhhhh\nh^hhh\n^^^^^', 'Draconian tower'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'hhh^^\nhhh^^\nhh^^^', 'Dwarf warehouse'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'ddddb\nddddb\nddddd', 'Gladiator training grounds'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'bjjbS\nbjjjb\nbbjjb', 'Ruins of Kofgaad'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'lfffl\nlffff\nlllfl', 'Monks'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'fffff\nfffff\nfffff', 'Alchemist guild'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'hhhdd\n^hhdd\n^dddd', 'Tarmalen autumn guild'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'jjjjj\njjjjj\njjjjj', 'Mage poison'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'~j^^^\n~~^V^\n~jj^b', 'Mage guild, electricity'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'jjjjj\njjjjj\njssjj', 'Tiger shrine (luce)'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'jjjjj\nj^#^j\njjjj^', 'Temple of Tzarakk'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'srjjj\nsrjjj\n~~~~~', 'Martial arts trainer (catfolk)'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'bSSSS\n.bbSS\n....S', 'Ranger (luc)'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'hhhh^\n^^hhh\nrrrrh', 'Barb (luc)'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'sssss\nsssss\nsssss', 'Priest (luc)'),
  (uuid_generate_v5 (uuid_nil(), 'lucentium'), E'FFFrR\njjjrR\njjjrR', 'Jungle cavalier'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'hhh^^\n^^h^^\n^^^^^', 'Aljerak temple'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^cccc\n=cccc\n^cccc', 'Rilynt''tar'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'~~SSF\n~~?SF\n~~|SF', 'Ril''ynttar harbour'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'FsFF~\nhh?F~\nsFss~', 'Elven Outpost'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'~~FFF\n~~?FF\n~~~FF', 'Manor'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'HHFFs\nFF?FF\nFFFsF', 'Samurai fort'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'ss~~~\nyy?S~\nyyyS~', 'Domgroth''s Mansion'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'sFFFF\nsF?FF\nFFFF/', 'Haunted Mansion'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'xxLL^\n^^?VL\n^^^L^', 'Volcano'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'@xxHH\n@^?HH\nV^^HH', 'Golem'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'FFFFF\nFF?FF\nFFFFF', 'Darkwood'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^^^^^\nH^?^^\nHHH\\-', 'Brantis'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'####x\n##?#x\nx#xxx', 'Perins'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'FFxxx\nxx?xx\nxxFFx', 'Mansion'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^^^^^\nhh?^^\n^hh^^', 'Tiamat'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'FxxFF\nFF?FF\nFFFFF', 'Temple of the Twisted Prophecies'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'hhhhh\nhh?,,\n^hhhh', 'Orthanc'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'hh^^^\n^h?^^\n^hh^^', 'Kutanakor, west entrance'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^^hh^\n^^?h^\n^^^h^', 'Kutanakor, east entrance'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^FFFF\nFF?FF\nFFFFh', 'Ikar'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^^^hh\n!^?hh\n^^hhL', 'Hell'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'sss^^\n~s?^^\n~~~~^', 'An old fort'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^^#^^\n^#?#^\n^hh^^', 'Tower of Corabandor'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'hVVVh\nVV?VV\nxxLLL', 'Fire giants'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'jjjjj\njj?jj\njjjjj', 'Ndoki'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'jjjjj\njj?jj\njjjjj', 'Cavemen'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'#h##b\n##?#b\n###bb', 'Atlantis'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'sFFFs\nFs?FF\nss,sF', 'Necromancer'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'FFFFF\nFs?FF\nFsFFF', 'Forest of the Moon'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'LLxxx\nLLxxx\nLLLxx', 'Castle Firefox'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'H^^^H\nx^L^H\n@@V^H', 'Citadel pit'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'hhhhh\n^^hhh\n^^^^h', 'Wanderer maze'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'sssss\nFFfss\nFsFFF', 'Abandoned house'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'SSjss\nrsjjj\nrsjjs', 'Trillazoo'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'sssss\nsssss\nsssss', 'Zonni swamps'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^^jjj\n^^jjj\n^^^jj', 'Savage jungle'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^^^^^\nHH?^^\nHHH^^', 'Cartwheel'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'FFFFF\n,,FFF\nFFFFF', 'Plakhstan'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E',##ss\n,###s\n,##ss', 'Temple of Chaos'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'~~~ss\n~~sss\n~~~ss', 'Furnachia fort (west)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'ssSSS\nsssSS\nsssSS', 'Furnachia fort (east)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'jjj~~\n~~j~~\n~~~~~', 'Furnachia fort (south)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'ss+--\ns/FsF\n/sFFF', 'Abandoned village'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'hhh^^\nhhh^^\nh^^^^', 'Mountain peak'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'FFF#F\n#F#FF\nFFFFF', 'Abandoned, ruined temple'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'slH^H\nll#^^\nl^^^^', 'Drow tower'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^^#LV\n^^##L\n^#^##', 'Priest guild special place'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'sshs~\nhhhh~\nsh^h~', 'Infection'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'FFFFH\nFFFFF\nFFFFH', 'Monk (furn)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'HFFFF\nHHFFF\nH^HFF', 'Ranger (furn)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'HH^^H\nHHH^H\nHHH^H', 'Barb (furn)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^^^^^\n^^hhh\nhhhhh', 'Martial arts trainer (dwarf)'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'HHHFF\nHH?FF\nHH^HF', 'Lords of chaos'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'^^^^^\n^^?^^\nLL^^^', 'Wanderer''s guild'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'hhVLL\nLh%hL\nxxhLL', 'Mage fire'),
  (uuid_generate_v5 (uuid_nil(), 'furnachia'), E'xxxxx\nxxxxx\nxxxxx', 'Badlands cavalier'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'^RcR^\nRcccR\n^RcR^', 'Calythien'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'HH~~~\n--?~~\nHHH~~', 'Windham'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'SSSSS\nSS?SS\nh,hhh', 'Seashore Tower'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'hFhhF\nFh?hh\n,,,,,', 'Dunamor'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'SSSSS\nhh?SS\n,,,hh', 'West wharf'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'~~~HH\n~~?HH\n~~v\\H', 'Sunderland'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'FHFHF\nFF?FF\nFFFFF', 'The Last Unicorn'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'..F.F\n.F?FF\n...F.', 'Teywaer Graveyard'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'h^^hh\n^^?Fh\n^FFFh', 'Teywaer Tunnel'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'FFFFF\nFF?FF\nFFFFF', 'Teywaer village'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'..F..\n.Ff..\n.FF.F', 'Teywaer well'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'^^^^^\n^^?^^\nvvv^^', 'Celestial Caverns'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'S...S\nSF..S\nh..SS', 'Goblin citadel'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'FFFFF\nFF?FF\nFFFFF', 'Well'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'rRvvv\nrR?vv\nrRrvv', 'Twisted tower'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'zh^^h\nh^?##\nzh##h', 'Cathedral'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'#####\n##?#l\n####l', 'Ruins of El Deagnoh'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'#^^^^\n#^?^^\n###^^', 'Halls of the Dead'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'^^^^v\n^^?vv\n^^vvv', 'Kobold mines'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'vvvvH\nvv?vv\nvvvvv', 'Tiburico'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'vvvvv\n^^?^^\n^^^^^', 'Castle of Toxic'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'h|h.S\nh+?.S\nhh\\.S', 'Seabird Inn'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'^^^HH\n^^?HH\n^^HHH', '51 daughters'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'^^^^^\nHH?^H\nsHHHH', 'The valley of silence'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'ff^^^\n--?^^\nHff^^', 'Tralpecktor'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'dddd^\ndd?dd\nddddd', 'The Ancient Temple of the Gods'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'~##..\n##?#h\n~##f.', 'Stone garden'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'^HHHH\n^^?HH\n^^^^^', 'The Warlock Conclave'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'ddddd\ndd?dd\nddddd', 'Tarackia'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'fffff\nff?fv\nff,ff', 'Brimshire'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'fffHv\nff?vv\nffvvv', 'Soy'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'fffff\nff?ff\nsffff', 'Hairikko Forest'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'vvvvv\nvv?vv\nvv|vv', 'The Temple of Pandion Knights'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'Hvvvv\nvv?vH\nvvvvH', 'Villager under attack'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'HH#HH\nH#?#H\nHH#HH', 'Ochimo'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'hhhhh\nsh?hS\nsh~SS', 'Red Tides'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'H^^^^\nHH?^^\nHH^^^', 'Caves of Orac'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'HH#H#\n##?#,\nv##HH', 'Ruins of a Temple of All Gods'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'####H\nH#?#H\nH####', 'DESO-UNKNOWN '),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'fsfss\nff?ss\nffHsf', 'Goblin Farm'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'fvHHH\nfv?Hf\nvvvHf', 'Mythical Valley'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'sssss\nsfsss\nffffs', 'Millie''s Nightmare'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'HyyFF\nHy?FF\nHH,Fl', 'Buckthorn Valley'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'fffff\nfffff\nfffff', 'The Lands of Apollo'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'^^^^~\n^^^^^\n^^svv', 'Magerathia'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'HH^^^\n...^^\n...^^', 'Tinmen Monastery'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'vvvvv\nvvvvv\nvvvvv', 'Abandoned barn'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'...ff\n.hhhf\nhhhhh', 'Snotling farm'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'^^^vv\n^^vvv\n^^vrr', 'Zorn'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'hhhhh\nhhhhh\nhhhhh', 'Feldspar conglomerate'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'vHHHH\nvvHHH\nvvvHH', 'Meadowshire'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'.....\n..,F.\nS,,.,', 'Broken Forest - Castle'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'S..,F\nSS,,.\n==,,,', 'Broken Forest - Barracks'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E',.,.S\n,,,SS\nSSSSS', 'Broken Forest - Seacrest'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'...SS\nF.,SS\n.,.SS', 'Broken Forest - Prison'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'HHHHH\nHHHHH\nHHHHH', 'Ranger (deso)'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'HHH^^\n^^HH^\n^^^H^', 'Barb (deso)'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'sslls\nsssls\nsssss', 'Priest (deso)'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'HH#HH\nz###H\nHH#HH', 'Midnight cavalier'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'hssss\nhs%ss\nhssss', 'Mage acid'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'vv,^^\n^^?^^\n^^^^^', 'Templar guild'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'sssss\nss?sH\nsssss', 'Tarmalen spring guild'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'^^hhh\n^^?hh\n^^^hh', 'Conjurer guild'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'^dddH\ndd?#d\ndd##d', 'Reaver guild'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'HHH##\nHHH##\nHH###', 'Tiger shrine (deso)'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'^^^^d\nd^ddd\nddddd', 'Aelena temple'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'/FFFF\nFFFFF\nFFFFF', 'Ghost liberator mansion'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'fffff\nfffff\nfffff', 'Animist guild'),
  (uuid_generate_v5 (uuid_nil(), 'desolathya'), E'fffff\nfffff\nfffff', 'The Navigators of the Tree');
